### ISSUE TITLE
Error for first and last wave

### ISSUE THREAD

**Issue by giulioberna** [Mensen/swa-matlab#2]
Get error each time the time-window for plotting the wave is out of boundaries of the recording.

---

Subscript indices must either be real positive integers or logicals.

Error in swa_ST_Explorer>update_SWPlot (line 489)
         set(handles.SWPlot.All(i),...

Error in swa_ST_Explorer>SpinnerUpdate (line 398)
handles = update_SWPlot(handles);

**Comment by Mensen** [comment]
I think I already fixed this in the new version... have a look.

I included this code

```
range = handles.SW(nSW).Ref_NegativePeak-win:handles.SW(nSW).Ref_NegativePeak+win;
range(range<1) = [];
```

So if the range (in samples) is less than one, ignore it. Now that I see this, it might be better to make these nan so that the window stays the same size rather than just get cut off.

I also need to add a similar thing for the end of the data boundaries...
