### ISSUE TITLE
SW Traveling

### ISSUE THREAD

**Issue by giulioberna** [Mensen/swa-matlab#20]
Hi Armand...
I was doing some tests with the SW traveling and noticed this check in your script swa_FindSWStreams:

Info.Parameters.Stream_MinDelay = 40; % minimum travel time (ms)

if max(Delays) < Info.Parameters.Stream_MinDelay \* Info.sRate/1000
        continue
end

If I understand correctly, despite the name of the variables you are actually checking that the traveling is not longer than 40ms. Correct? Is there a specific reason for this check (and this particular value)?

Thanks

**Comment by Mensen** [comment]
Almost correct, it makes sure that the longest delays are at least 40ms such that all travelling parameters are calculated for longer travelling times.

The idea here is that if the wave does not travel for at least 40ms over the scalp, it shouldn't really be regarded as a 'travelling' wave and the travelling parameters are ignored.

Of course one might still be interested in the travelling parameters of very quick/very local waves so that is why it is an adjustable parameter.
