### ISSUE TITLE
angles maps

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#21]
Which is the correct orientation? Probably you told me, but I can't remember.
By the way it would be nice to add this information somewhere

**Comment by Mensen** [comment]
I am 99% sure that the orientation that is plotted on the angle map is true to the orientation of the topographies. That is why I didn't specify this anywhere since it is precisely what one would expect.

That is, an angle of 0 degrees, which is plotted to the right in the angle map, represents traveling waves moving from left to right. In the same way, 90 degrees represents waves traveling from the posterior channels to the frontal channels.

**Comment by AnnaCastelnovo** [comment]
Ok, It was just that several months ago you told me something about the orientation, but I couldn't remember. so I was not totally sure. Many thanks!
