### ISSUE TITLE
question on 256 vs 185 format

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#27]
Hi Armand,

I created a set file with 185 channels and the corresponding chanlocs with 185 channels (but with the original labels (so for ex the last one is 224) in order to run the toolbox with 185 channels only. 
1) is it correct or there is a problem with the labelling and I have to rename them from 1 to 185?
2) is there a smarter way to do this with the toolbox, maybe an option I didn't see?
Thanks,

Anna

**Comment by Mensen** [comment]
There should be no problem with the way you have them. The electrode labels are only used for plotting purposes and don't affect any part of the calculation.

For example, the current dataset I'm working with used the classic 10-20 system and has electrode labels like C3-C4 etc, so the names of the channels really don't matter. 

However, I would suggest naming the channels with something like an "E" as a prefix so that channel 224 is called "E224". Otherwise there might be some confusion when any visualisation is referring to the electrode by label or by number in the channel series.

**Comment by AnnaCastelnovo** [comment]
ok thanks much!
