### ISSUE TITLE
Backward streamlines option

### ISSUE THREAD

**Issue by giulioberna** [Mensen/swa-matlab#3]
Backward streamlines seem a bit confusing sometime as they can reach electrodes quite far from the supposed origin. As far as I understood forward and backward streamlines are pooled together in the results. However, backward streamlines could be difficult to interpret and one may prefer to look only at forward streamlines. I think it would be nice to have an option to deactivate backward streamlines, or at least, to have a variable with indices indicating the type (FWD, BWD).

**Comment by Mensen** [comment]
So the plotting functions for the waves in this case just look at the saved data in ST(n).Travelling_Streams field. So changing this would be changing the calculation in swa_FindSTTravelling.m

In particular 

```
    for i = 1:length(sx)
        [StreamsBack, DistancesBack,~] = adstream2b(XYrange,XYrange,-u,-v,sx(i),sy(i), cosd(45), 0.1, 1000);
        [StreamsForw, DistancesForw,~] = adstream2b(XYrange,XYrange,u,v,sx(i),sy(i), cosd(45), 0.1, 1000);
        Streams{i}      = [fliplr(StreamsBack), StreamsForw];
        Distances{i}    = [fliplr(DistancesBack), DistancesForw];
    end
```

Above we have the separate calculation and then combine the two in later. We could keep things separate from this point on instead of combining them... but later on we look for all the longest streamlines...

```
    tDist = cellfun(@(x) sum(x), Distances);    %% Plot Functions
    [~,maxDistId] = max(tDist);
    if maxDistId ~= maxDispId
        ST(nST).Travelling_Streams{end+1} = Streams{maxDistId};
    end  
```

and keeping them separate won't give us the longest ones anymore, so this part would need tweaking too in this case.

Its definitely worth considering to make it optional, but the streamline in this case might give a better idea (or at least different) of the origin than just the earliest peak without looking at topography.

**Comment by giulioberna** [comment]
I think make it optional would be the best solution. I mean... I can simply remove the line for backward streamlines calculation from the code, but since BWD streamlines could be difficult to interpret (they have a different origin than the one calculated based on latencies) I'm probably not the only one who would prefer to not include them when defining the longest streamline.
