### ISSUE TITLE
reduce number of channels and stages

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#30]
Hey Armand,
I think you already addressed the issue of how to select stages and channels after the sw detection, but .. where? (name of the script?)
Thanks,

Anna

**Comment by Mensen** [comment]
Hey Anna,

That depends on the preprocessing steps you used after you scored your data; in particular whether you removed any stages after you scored.

Removing channels is as easy as simply deleting the ones you don't want from the data matrix in the structure... e.g.

`Data.Raw(1:10, :) = [];`

Removing waves from certain stages is more difficult if the scoring information no longer matches the timing of the data, like when you have removed segments. In the SW structure you have the timing (in samples) of each wave, but somewhere you need to have other information about whether that particular time was scored as N2 or N3 (I assume those are the stages you wish to separate).

If you haven't removed any time periods since scoring then you can get the timings from the SW structure as (maybe there is a coding mistake since I'm writing these commands by memory)...

`SW_timing = [SW.Peak_Ind]`

and the samples corresponding to that particular stages as 

`N2_samples = find(EEG.swa_scoring.stages == 2);`

and then find the waves that correspond to that timing with 

`good_waves = ismember(SW_timing, N2_samples);`

In the other case that you have removed samples, and didn't keep track of which samples were removed then you have lost the scoring information essentially (since the timing no longer matches up), and I would recommend loading the relevant EEG file into the swa_scoring and quickly scoring the reduced dataset again.

**Comment by AnnaCastelnovo** [comment]
Thanks Armand
Actually I removed channels and kept track of what I rejected. And in the
past I just input the toolbox exactly what I wanted (i.e. 256 cleaned data,
or 173 N3 only or N23 together etc)

Yet, I was wandering if there was a smarter way than rerunning the same
thing for 256 and 173 channels and for N23 and N2 and N3. I mean, the part
'detect slow waves for each channel is the same. Yet, it's no longer the
same fro delays and travelling I guess, so I was wandering if there was a
way to avoid to recalculate waves for each channels.
(awful explanation I know, hope what I wrote is understandable ...)

2015-10-26 11:08 GMT-05:00 Armand Mensen notifications@github.com:

**Comment by Mensen** [comment]
Well, if you have one results file that you are happy with then you could remove the channels you are not interested in from just the SW structure, and the Info structure. So instead of each SW.Channels_Active being 256 long, it would be 173 long (side-note: why not 257? Do you not put Cz back into your data when you re-reference?).

As for the stages... if you know what samples you rejected in pre-processing then you can just reject and delete those samples from the scoring information too (EEG.swa_scoring.stages). This way, the scoring information and the data should be the same length, and you can quickly eliminate the waves which begin during a certain stage as I indicated before with... 

``` matlab
SW_timing = [SW.Peak_Ind];
N2_samples = find( new_scoring_vector == 2);
good_waves = ismember(SW_timing, N2_samples);
```

where the `new_scoring_vector` is just the `EEG.swa_scoring.stages` with the same samples removed as you did with your actual data since you said you kept track of everything you removed.

**Comment by Mensen** [comment]
Also... if you do happen to run the toolbox again for different datasets I would highly recommend taking the exact same settings for each run. Most importantly, I would set the amplitude criteria to "absolute" and use the same amplitude threshold for each of the datasets. If you use the relative criteria it will re-calculate the standard deviation from the mean of the new dataset and you might find different waves between N2 and N3 than when you had N23 combined.

**Comment by AnnaCastelnovo** [comment]
ok thanks all clear
just .. so the delay maps will not be affected by removing channels? I was
a little bit concern..
thanks much for the clarifications!

2015-10-27 3:41 GMT-05:00 Armand Mensen notifications@github.com:

**Comment by Mensen** [comment]
Indeed, the delay maps would certainly be affected by removing channels. Although how much that will affect your parameters of interest depends on what they are. Ultimately, what are you looking for in the slow waves? If you're interested in some travelling parameter then best to re-run the swa_FindSWChannels part with the removed channels. Otherwise, it might not matter.
