### ISSUE TITLE
amplitude plots

### ISSUE THREAD

**Issue by AnnaCastelnovo** [Mensen/swa-matlab#35]
Hi Armand, 

why did you prefer to calculate the amplitude like the minimum ---> amplitudes_hc{i,:} = min([SW.Channels_NegAmp]); rather than the mean? Am I missing something?
Plus, I found useful also plotting the amplitude topography, it might be nice to add it too?
Say hello to Madison for me!

**Comment by Mensen** [comment]
Hey Anna!

Where did you find the code:

`amplitudes_hc{i,:} = min([SW.Channels_NegAmp]);`

Certainly not part of any toolbox script. The `i` there tells me its in a loop somewhere. But it wouldn't be part of my code since I try to stay away from using `i`.

There is an intensity plot option for individual waves in the `swa_Explorer` but you're right in that adding some summary measure of amplitude topography would be helpful.

**Comment by AnnaCastelnovo** [comment]
Hey  Armand!

ops:
I clearly wrote it, I was trying to refer to part of your code in swa_wave_summary.

  % for SW and ST
        if isfield(SW, 'Channels_NegAmp')
            output = min([SW.Channels_NegAmp]);
        else
            output = max([SW.Channels_Peak2PeakAmp]);
        end

Why the smallest wave and not the mean of all the waves detected by each channel? (if I am not missing something, that's probably the case...)

Now I am so ashamed I will never use the variable "i'' again.

**Comment by Mensen** [comment]
I see now.

So the minimum amplitude (the largest negative) is more representative of the potential strength of the wave than the mean would be.

Consider a local wave that has a peak of -100uV, and another global wave with the same -100uV peak. Since the global wave will have more channels less than the -100uV, its mean will be substantially lower than the local waves mean. However, I would consider the strength of each wave to be the same.

So given differences in the locality of each wave, the minimum is a better estimate of the strength of the wave. 

Perhaps some mean amplitude, while talking the locality into account would be another possible measure of wave strength, but I'm not sure how this would work exactly.

**Comment by AnnaCastelnovo** [comment]
Oh, I see now, got it!
Thanks,

Anna
Il 11/dic/2015 10:55 PM, "Armand Mensen" notifications@github.com ha
scritto:
