### ISSUE TITLE
swa_FindSSRef error when set window

### ISSUE THREAD

**Issue by arnaudbore** [Mensen/swa-matlab#37]
Hi,
In swa_FindSSRef.m file line 90

window = ones((Info.Parameters.Filter_Window \* Info.Recording.sRate), 1) /...
        (Info.Parameters.Filter_Window \* Info.Recording.sRate);

Info.Parameters.Filter_Window = 0.15
Info.Recording.sRate = 250

I get this error:

Size inputs must be integers.
Error in swa_FindSSRef (line 90)
    window = ones((Info.Parameters.Filter_Window \* Info.Recording.sRate), 1) /...
Error in swa_SS_Template (line 88)
[Data, Info, SS, SS_Core] = swa_FindSSRef(Data, Info);

I would like to know how does it work for you ?
Thank you
Arnaud

**Comment by Mensen** [comment]
Turns out that I had always been really lucky with my filtering window size and sampling rate so that I always got an integer when multiplying the two.

The value is now 'floored' so that it gets the sampling window closest to the desired values, but that is still an integer value.

Good luck with your analysis! Let me know if there are any more features or bugs and I'll be happy to fix them.

**Comment by arnaudbore** [comment]
I just found out that depending on the matlab version you are using ones function can work with float. In R2012b for exemple there is no error and it runs it like if it were "floored".

Thanks for your help.
