### ISSUE TITLE
first analyzes

### ISSUE THREAD

**Issue by colamartinoelis** [Mensen/swa-matlab#40]
Hello,

I'm starting for the first time to make the sleep analysis and I think that your toolbox could be helpful for me. I know eeglab and some matlab functions.

My goal is to detect sleep wave automatically so I think that your toolbox could be useful. However I don't understand where to begin. I used the examples that I found in the template but I'm not able to make them work.

I want to specify that my files have only 4 channels, so it should be simpler.

My apologies for the very simple problem, I hope you could help me.

Thank you.

**Comment by Mensen** [comment]
@vetriol 

No problem... in the case of 4 channels, you are probably best off using the toolbox in a slightly different way than the standard procedure since this is optimized for high-density recordings.

First you can load your data from the EEGLAB format...

`[Data, Info] = swa_convertFromEEGLAB();`

Get the default detection parameters (and change any you like directly)

`Info = swa_getInfoDefaults(Info, 'SW', 'envelope');`

Filter, and specify your 4 channels as the canonical/reference wave (rather than calculating the negative envelope or some regional reference).

`Data.SWRef = swa_filter_data(Data.Raw, Info);`

Then just calculate the waves in that reference (which is actually all your data).

`[Data, Info, SW] = swa_FindSWRef (Data, Info);`

The SW structure will have lots of the information you are looking for... but in case something is not clear just let me know and I'll try and help or add some features.

Unfortunately you won't be able to use many of the plotting tools available for the toolbox because the SW structure is missing some key elements running it this way, but perhaps I can help out there too if you let me know what you are looking for.

**Comment by colamartinoelis** [comment]
Thank you very much Mensen, now I'm able to do what you wrote me.
I have just another question:
in the the SW structure I have several Fields but: which is the range of every Field?

Thanks again

**Comment by Mensen** [comment]
I'm glad that worked. 

I'm not sure what you mean by range of each field?

In the SW structure each field is a certain property of the slow wave found. The size of the SW structure is the number of slow waves total in your dataset.

**Comment by colamartinoelis** [comment]
Thanks again Mensen! 
In this week I've worked for this project and now I think to understand. 
Your script is very useful for me.

**Comment by Mensen** [comment]
Glad to hear. Let me know if you have any other issues or features you'd like to see. I'm happy to hear suggestions.
