### ISSUE TITLE
How to get frequency's spindle in FindSSRef

### ISSUE THREAD

**Issue by arnaudbore** [Mensen/swa-matlab#42]
Hi Armand,

Using your function FindSSRef I get spindle type (slow or false) but I need to characterize each spindle with its frequency. Is there a way to get the frequency of each spindle ?

Thank you in advance for your help.
Arnaud

**Comment by Mensen** [comment]
Since the algorithm uses wavelets to find the spindles, we can differentiate between the fast and slow ones fairly easily, but wavelet scales don't necessarily correspond perfectly to frequencies.... so there is no specific output for the frequency peak of each spindle.

However, I could put in an additional function that re-examines each spindle found and then runs an FFT between the start and end markers of the spindles and outputs the results, or even just outputs the normalized peak. This should be too much to implement if that makes sense to you.

You could also of course do this, if you know what to do and contribute that function to the toolbox?

Let me know if you think I should make this function.

**Comment by arnaudbore** [comment]
I understand that using a step of .5 for each wavelet could lead to a wrong frequency approximation but I use a 0.1 step for the wavelet decomposition to get a more accurate frequency. Could it still be a good way to get the frequency or do we need FFT ?

**Comment by Mensen** [comment]
Unfortunately, the current implementation means the wavelet coefficients for the slow and fast bands to give an estimate of which is more likely to be the case. So the specific peak is lost in the mean unfortunately. I don't think it would be too difficult to change, so I'll have a look into the code and see if it would be efficient to keep the original wavelets and then for each spindle estimate the peak pseudo-frequency.

Let me get back to you on this.

**Comment by Mensen** [comment]
So, I made a couple changes to the spindle detection and one includes finding the peak frequency of each spindle and saving this in the output...

This change was made in f25285708ced6748f5cd35d3077d43811abf988f

I'll be working on aspects of spindle detection over the next couple weeks, so some other things might change in the next little while.
