### ISSUE TITLE
Absolute amplitude criteria

### ISSUE THREAD

**Issue by sfattinger** [Mensen/swa-matlab#44]
Hi Armand,
Thank you very much for your fast response. It would be great if there is another solution for the channel cluster testing. I have one other question: If I include an absolute amplitude criteria (let’s say 60) will this threshold of 60 µV go from negative to positive peak (peak to peak) or does it only mean, that the negative amplitude at the reference channel has to be lower than 60 µV? And what about all the other channels where a slow wave were detected? Does the negative amplitude of these waves also need to be below 60 µV to be detected?
Thank you very much.
Sara

**Comment by Mensen** [comment]
So, I was interested in seeing just how slow the single dimension cluster test would be in matlab so I made one this morning and its super fast so that is now the default behaviour of the toolbox and you should be able to use the parameter without the mex file working. 

The commit for this is 82891fb2fdc13030dfc824ccefe441ec38fc869e so you can see how I did it.

The negative amplitude threshold is an absolute value of the negative peak; there is another parameter for peak to peak threshold that you can set... but is ignored if you are using the negative envelope canonical wave (the reference channel... but I've stopped calling it reference to avoid confusion with EEG references).

The behaviour at the channel level is determined by the parameter setting for `Info.Parameters.Channels_Detection`. If its set to "correlation" than the absolute value at the channel level doesn't matter, and only the correlation matters. If its set to "threshold", than it adjusts all the criteria to the ratio supplied there e.g. if you had an original threshold of 100uV, and then a parameter setting of 0.6, then the individual channel would need to be 60uV.

Sounds a little crazy written like that, but hopefully its clear.

**Comment by sfattinger** [comment]
Thank you very much for your fast response and the adaptation.
Best,
Sara
