### ISSUE TITLE
Travelling_Delays

### ISSUE THREAD

**Issue by sfattinger** [Mensen/swa-matlab#46]
Hi Armand,
What is the exact Information that is stored in the variable SW.Travelling_Delays? I am playing around and I noticed, that there are several channels with a delay of 0 at completely independent and different locations (e.g. at ch 63 & and 64 and also at ch 100 & 120). How do I have to interpret this findings? Is there something wrong with the wave detection?
Thank you very much,
Best,
Sara

**Comment by Mensen** [comment]
This field stores the relative delays (compared to the earliest waves) for all channels. By default the delay is calculated as the earliest cross-correlation, but you can set it to the more classic, earliest negative peak in the parameter options.

Finding some waves with a few independent origins, or general delays that don't quite fit, is quite normal. Although I would agree that this is in principle a problem. Most of the time when I look at the channels, its right that both of those channel sets show an early wave and not just noise (although that happens to). 

Physiologically, perhaps it can be accounted for by the fact that the true origin of these waves is hidden from EEG (e.g. thalamus), and those regions that seem independent just happen to be the first connections of the true hidden origin. But without intracranial recordings, this is little more than speculation.

**Comment by sfattinger** [comment]
Thank you very much for you answer. Where can I change the detection to the earliest negative peak in the parameter options (Info.Parameters.???) I did not find it.
Thank you very much
Sara

**Comment by Mensen** [comment]
This change involves changing from the "correlation" method of channel detection to the "threshold" detection method for `Info.Parameters.Channels_Detection` ... just note that a few other results will also change; mainly that other channels are found using the amplitude and wavelength criteria set elsewhere and no longer just if they correlate with the canonical wave.

As a general note, determining wave origins is a tricky business and not something I feel great about yet since there are several potential ways to calculate when and where a wave starts and they are all reasonably justified but often produce very different results.
